name: blockchainproject
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  web3dart: ^2.5.0
  http: 1.2.2
  google_fonts: ^6.2.1
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  firebase_auth: ^5.1.3
  firebase_core: ^3.3.0  
  cloud_firestore: ^5.2.0
  fluttertoast: ^8.2.6
  shared_preferences: ^2.2.3  
  another_flutter_splash_screen: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/images/