name: blockchainproject
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: 1.2.2
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  firebase_auth: ^5.1.3
  firebase_core: ^3.3.0  
  cloud_firestore: ^5.2.0
  fluttertoast: ^8.2.6
  shared_preferences: ^2.2.3  
  another_flutter_splash_screen: ^1.2.1
  animated_text_kit: ^4.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/images/app_icon.png
    - assets/images/Designer.jpeg
    - assets/images/Designer (1).jpeg
    - assets/images/Designer (2).jpeg
    - assets/images/Designer (3).jpeg

    